version: '3.8'

x-common-web-config: &common-web-config
  build: .
  depends_on:
    db_dev:
      condition: service_healthy

services:
  web_dev:
    <<: *common-web-config
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    env_file:
      - .env.dev
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: >
      command: >
      sh -c "chmod +x /app/script.sh &&
             alembic upgrade head &&
             /app/script.sh"

  db_dev:
    image: postgres:13
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - .env.dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  default:
    name: myapp_dev_network

volumes:
  postgres_data_dev: