"""hacks

Revision ID: 0a9abed6359c
Revises: 858bc67aa1c9
Create Date: 2024-08-05 11:39:46.773486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a9abed6359c'
down_revision: Union[str, None] = '858bc67aa1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hacks', 'hack_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('hacks', 'date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('hacks', 'incident_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('hacks', 'consequences',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('hacks', 'mitigation_measure',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('hacks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hacks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('hacks', 'mitigation_measure',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('hacks', 'consequences',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('hacks', 'incident_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('hacks', 'date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('hacks', 'hack_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
