"""Coin bot table updated - is active

Revision ID: 2a9252ae02f4
Revises: 74a6ad6c13d3
Create Date: 2024-09-10 09:11:16.898883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9252ae02f4'
down_revision: Union[str, None] = '74a6ad6c13d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coin_bot', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coin_bot', 'is_active')
    # ### end Alembic commands ###
