"""Add unique constraint to purchased_plan table

Revision ID: 40f27339fda2
Revises: 82e43a1c2ab4
Create Date: 2024-09-14 18:26:59.893297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40f27339fda2'
down_revision: Union[str, None] = '82e43a1c2ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.alter_column('purchased_plan', 'reference_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('purchased_plan', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchased_plan', 'is_subscribed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint('uq_user_plan', 'purchased_plan', ['user_id', 'reference_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_plan', 'purchased_plan', type_='unique')
    op.alter_column('purchased_plan', 'is_subscribed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('purchased_plan', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('purchased_plan', 'reference_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
