"""is essential added to chart

Revision ID: a6fd97d66e5a
Revises: ca321a4118e6
Create Date: 2024-11-07 11:51:01.087708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6fd97d66e5a'
down_revision: Union[str, None] = 'ca321a4118e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.Inspector.from_engine(conn)
    columns = [column['name'] for column in inspector.get_columns('chart')]

    # Si 'is_essential' no existe en la tabla 'chart', agregar la columna
    if 'is_essential' not in columns:
        op.add_column('chart', sa.Column('is_essential', sa.Boolean(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chart', 'is_essential')
    # ### end Alembic commands ###
