"""Add new column in topics

Revision ID: e7ee74b7b181
Revises: 6562a81a7c5c
Create Date: 2024-10-09 13:20:05.423134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7ee74b7b181'
down_revision: Union[str, None] = '6562a81a7c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('type', sa.String(), nullable=False, server_default='default'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'type')
    # ### end Alembic commands ###
