"""added relationship between the Admin and the API Key schema

Revision ID: e9b1d398537c
Revises: 3720552336cb
Create Date: 2024-09-17 13:19:33.806277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9b1d398537c'
down_revision: Union[str, None] = '3720552336cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(None, 'api_keys', ['admin_id'])
    # op.create_foreign_key(None, 'api_keys', 'admins', ['admin_id'], ['admin_id'], ondelete='CASCADE')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'api_keys', type_='foreignkey')
    # op.drop_constraint(None, 'api_keys', type_='unique')
    pass
    # ### end Alembic commands ###
