"""Update analysis schema with image_url column

Revision ID: ed76f5dc38dc
Revises: c579d704997e
Create Date: 2024-09-11 12:48:08.946304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed76f5dc38dc'
down_revision: Union[str, None] = 'c579d704997e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('analysis', sa.Column('image_url', sa.String(), nullable=True))
    op.alter_column('analysis_image', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('narrative_trading', sa.Column('image', sa.String(), nullable=True))
    op.alter_column('user_table', 'nickname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_table', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_table', 'auth_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'user_table', ['auth_token'])
    op.create_unique_constraint(None, 'user_table', ['nickname'])
    op.create_unique_constraint(None, 'user_table', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_table', type_='unique')
    op.drop_constraint(None, 'user_table', type_='unique')
    op.drop_constraint(None, 'user_table', type_='unique')
    op.alter_column('user_table', 'auth_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_table', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_table', 'nickname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('narrative_trading', 'image')
    op.alter_column('analysis_image', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('analysis', 'image_url')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
