"""updated user schema: added birth_date field

Revision ID: f5d9fda86672
Revises: c579d704997e
Create Date: 2024-09-13 17:34:10.504027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d9fda86672'
down_revision: Union[str, None] = 'c579d704997e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'image_url')
    op.alter_column('analysis_image', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('narrative_trading', 'image')
    op.add_column('user_table', sa.Column('birth_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'birth_date')
    op.add_column('narrative_trading', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('analysis_image', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('analysis', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
